name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Validate HTML
        uses: micmro/html-validator-action@v2
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.3.3
        with:
          GITHUB_TOKEN: ${{ secrets.WEBSECRET }}
          BRANCH: web
          FOLDER: .
