name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Шаг 1: Checkout репозитория
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    # Шаг 2: Установка зависимостей
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        sudo npm install -g less
        
    # Шаг 3: Компиляция LESS в CSS
    - name: Compile LESS
      run: |
        lessc styles/styles.less styles/styles.css
        
    # Шаг 4: Минификация CSS и JavaScript
    - name: Minify CSS and JavaScript
      run: |
        # Установка инструментов минификации
        npm install -g cssnano
        npm install -g uglify-js
        
        # Минификация CSS
        cssnano css/main.css > styles/styles.min.css
        
        # Минификация JavaScript
        uglifyjs js/main.js -c -m -o scripts/script.min.js
        
    # Шаг 5: Проверка файлов
    - name: Check Files
      run: |
        ls -la css/styles.css
        ls -la styles/styles.min.css
        ls -la scripts/script.min.js
        
    # Шаг 6: Развертывание
    - name: Deploy to Server
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.WEBSECRET }}
        publish_dir: ./
        
    # Шаг 7: Отправка логов
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: deployment-logs
        path: |
          styles/
          scripts/
          *.log
